import type { PalabraEntry } from "./types";

/**
 * Starter bank (120+ items) — replace / merge with AI-generated sets later.
 * `acceptedEn` holds synonyms the player can type.
 */
export const PALABRA_WORD_BANK: PalabraEntry[] = [
  { id: "hola", es: "hola", en: "hello", acceptedEn: ["hi", "hey"], hint: "The default greeting any time of day.", example: "¡Hola, buenos días!" },
  { id: "adios", es: "adiós", en: "goodbye", acceptedEn: ["bye"], hint: "Formal farewell; friends often say hasta luego.", example: "Adiós, nos vemos mañana." },
  { id: "gracias", es: "gracias", en: "thank you", acceptedEn: ["thanks"], hint: "Core politeness — often doubled: muchas gracias.", example: "Gracias por tu ayuda." },
  { id: "por-favor", es: "por favor", en: "please", hint: "Softens requests; place before or after the ask.", example: "Un café, por favor." },
  { id: "si", es: "sí", en: "yes", hint: "Written with accent to distinguish from 'if' (si).", example: "¿Te gusta? — Sí." },
  { id: "no", es: "no", en: "no", hint: "Same spelling as English; tone is everything.", example: "No, gracias." },
  { id: "perdon", es: "perdón", en: "sorry", acceptedEn: ["excuse me", "pardon"], hint: "Bump someone or interrupt — perdón.", example: "Perdón por el retraso." },
  { id: "buenos-dias", es: "buenos días", en: "good morning", hint: "Until lunch-ish; after that use buenas tardes.", example: "Buenos días, ¿cómo estás?" },
  { id: "buenas-tardes", es: "buenas tardes", en: "good afternoon", acceptedEn: ["good evening"], hint: "Covers afternoon into early evening.", example: "Buenas tardes, señora." },
  { id: "buenas-noches", es: "buenas noches", en: "good night", acceptedEn: ["good evening"], hint: "Greeting at night or goodbye before bed.", example: "Buenas noches, que descanses." },
  { id: "como-estas", es: "¿cómo estás?", en: "how are you", acceptedEn: ["how are you?"], hint: "Tú form; formal: ¿cómo está (usted)?", example: "Hola, ¿cómo estás?" },
  { id: "muy-bien", es: "muy bien", en: "very well", acceptedEn: ["great", "fine"], hint: "Standard positive reply.", example: "Estoy muy bien, gracias." },
  { id: "mucho-gusto", es: "mucho gusto", en: "nice to meet you", acceptedEn: ["pleased to meet you"], hint: "After introductions; reply: igualmente.", example: "Mucho gusto, soy Ana." },
  { id: "de-nada", es: "de nada", en: "you're welcome", acceptedEn: ["no problem"], hint: "Literally 'of nothing' — super common.", example: "Gracias — De nada." },
  { id: "agua", es: "agua", en: "water", hint: "Feminine but takes el in singular (el agua) — exception!", example: "Un vaso de agua, por favor." },
  { id: "pan", es: "pan", en: "bread", hint: "Corner panaderías smell like heaven.", example: "Compramos pan fresco." },
  { id: "leche", es: "leche", en: "milk", hint: "Café con leche is a breakfast staple in Spain.", example: "No tomo leche." },
  { id: "cafe", es: "café", en: "coffee", acceptedEn: ["coffee"], hint: "Accent on é; un café is an espresso in many bars.", example: "Un café solo, por favor." },
  { id: "cerveza", es: "cerveza", en: "beer", hint: "Tapas + caña (small draft) = classic.", example: "Dos cervezas, por favor." },
  { id: "vino", es: "vino", en: "wine", hint: "Rioja, Ribera, Albariño — endless geography.", example: "Una copa de vino tinto." },
  { id: "arroz", es: "arroz", en: "rice", hint: "Paella's soul; short-grain in Valencia.", example: "El arroz está delicioso." },
  { id: "pollo", es: "pollo", en: "chicken", hint: "Pollo al ajillo — garlic chicken.", example: "Me gusta el pollo a la plancha." },
  { id: "pescado", es: "pescado", en: "fish", hint: "Coastal menus shine; ask what's fresh.", example: "Hoy hay pescado del día." },
  { id: "queso", es: "queso", en: "cheese", hint: "Manchego is the famous sheep's milk wheel.", example: "Una tabla de quesos, por favor." },
  { id: "huevo", es: "huevo", en: "egg", hint: "Tortilla española is thick potato omelette.", example: "Dos huevos fritos." },
  { id: "fruta", es: "fruta", en: "fruit", hint: "Mercados sell seasonal fruit by the kilo.", example: "Compra fruta madura." },
  { id: "verdura", es: "verdura", en: "vegetables", acceptedEn: ["greens", "veggies"], hint: "Often plural verduras in everyday speech.", example: "Come más verdura." },
  { id: "carne", es: "carne", en: "meat", hint: "Also means 'flesh' in literature.", example: "No como carne los lunes." },
  { id: "azucar", es: "azúcar", en: "sugar", hint: "Accent on ú; café sin azúcar.", example: "Con poco azúcar, por favor." },
  { id: "sal", es: "sal", en: "salt", hint: "Echar sal — to add salt.", example: "Pásame la sal." },
  { id: "mesa", es: "mesa", en: "table", hint: "Mesa redonda — round table (talks).", example: "Reservamos una mesa para dos." },
  { id: "silla", es: "silla", en: "chair", hint: "Sillón is a big armchair.", example: "Siéntate en esa silla." },
  { id: "puerta", es: "puerta", en: "door", hint: "Puerta can mean gate (de la ciudad).", example: "Cierra la puerta, por favor." },
  { id: "ventana", es: "ventana", en: "window", hint: "Ventanal — large window.", example: "Abre la ventana, hace calor." },
  { id: "casa", es: "casa", en: "house", acceptedEn: ["home"], hint: "En casa — at home.", example: "Vuelvo a casa tarde." },
  { id: "calle", es: "calle", en: "street", hint: "Callejear — to wander streets.", example: "Vivo en esta calle." },
  { id: "ciudad", es: "ciudad", en: "city", hint: "Ciudadano / ciudadana — citizen.", example: "Madrid es una ciudad enorme." },
  { id: "playa", es: "playa", en: "beach", hint: "Verbenas and chiringuitos in summer.", example: "Vamos a la playa mañana." },
  { id: "montana", es: "montaña", en: "mountain", acceptedEn: ["mountain"], hint: "Pyrenees, Sierra Nevada — great hiking.", example: "Subimos la montaña al amanecer." },
  { id: "sol", es: "sol", en: "sun", hint: "Hace sol — it's sunny.", example: "Hoy hace mucho sol." },
  { id: "luna", es: "luna", en: "moon", hint: "Luna de miel — honeymoon.", example: "La luna está llena." },
  { id: "estrella", es: "estrella", en: "star", hint: "Estrella Michelin — fine dining fame.", example: "Miles de estrellas en el cielo." },
  { id: "rojo", es: "rojo", en: "red", hint: "Rojo pasión — flamenco dresses.", example: "El semáforo está en rojo." },
  { id: "azul", es: "azul", en: "blue", hint: "Mar azul — classic song reference territory.", example: "Me gusta el azul marino." },
  { id: "verde", es: "verde", en: "green", hint: "Enverdecer — to turn green (spring).", example: "Los campos están verdes." },
  { id: "amarillo", es: "amarillo", en: "yellow", hint: "Amarillo — caution in many signs.", example: "Un vestido amarillo precioso." },
  { id: "negro", es: "negro", en: "black", hint: "Café negro — black coffee.", example: "Prefiero el café negro." },
  { id: "blanco", es: "blanco", en: "white", hint: "Blanco y en botella — obvious (milk joke).", example: "Las paredes son blancas." },
  { id: "uno", es: "uno", en: "one", hint: "Un / una agree with gender.", example: "Solo quiero uno." },
  { id: "dos", es: "dos", en: "two", hint: "Dos besos greeting in parts of Spain.", example: "Somos dos hermanos." },
  { id: "tres", es: "tres", en: "three", hint: "Tres leches cake crosses borders.", example: "Cuenta hasta tres." },
  { id: "diez", es: "diez", en: "ten", hint: "Diez minutos — ten minutes (often elastic).", example: "Son las diez en punto." },
  { id: "cien", es: "cien", en: "hundred", acceptedEn: ["one hundred"], hint: "Ciento before nouns: ciento uno.", example: "Cien personas en la fila." },
  { id: "hoy", es: "hoy", en: "today", hint: "Hoy por hoy — nowadays.", example: "Hoy hace frío." },
  { id: "manana", es: "mañana", en: "tomorrow", acceptedEn: ["morning"], hint: "Same word as 'morning' — context decides.", example: "Te llamo mañana." },
  { id: "ayer", es: "ayer", en: "yesterday", hint: "Ayer y hoy — then and now.", example: "Ayer fuimos al museo." },
  { id: "ahora", es: "ahora", en: "now", hint: "Ahora mismo — right now.", example: "Salgo ahora mismo." },
  { id: "siempre", es: "siempre", en: "always", hint: "Para siempre — forever.", example: "Siempre llegas tarde." },
  { id: "nunca", es: "nunca", en: "never", hint: "Nunca jamás — emphatic never.", example: "Nunca digas eso." },
  { id: "tarde", es: "tarde", en: "afternoon", acceptedEn: ["late"], hint: "Buenas tardes / llegar tarde.", example: "Llegué tarde al tren." },
  { id: "noche", es: "noche", en: "night", hint: "De la noche a la mañana — overnight.", example: "Trabajo de noche." },
  { id: "lunes", es: "lunes", en: "monday", hint: "Week starts on Monday in calendars.", example: "El lunes empieza el curso." },
  { id: "viernes", es: "viernes", en: "friday", hint: "Viernes noche — social energy peaks.", example: "¡Por fin es viernes!" },
  { id: "sabado", es: "sábado", en: "saturday", acceptedEn: ["saturday"], hint: "Accent on first á.", example: "El sábado hay mercado." },
  { id: "domingo", es: "domingo", en: "sunday", hint: "Dominguero — Sunday driver vibe.", example: "Los domingo descanso." },
  { id: "enero", es: "enero", en: "january", hint: "Reyes — January 6 gifts in Spain.", example: "Nací en enero." },
  { id: "julio", es: "julio", en: "july", acceptedEn: ["july"], hint: "Peak heat in much of Spain.", example: "En julio vamos al pueblo." },
  { id: "madre", es: "madre", en: "mother", acceptedEn: ["mom", "mum"], hint: "Madre mía — oh my!", example: "Mi madre cocina genial." },
  { id: "padre", es: "padre", en: "father", acceptedEn: ["dad"], hint: "Padre also slang for 'cool' in Mexico.", example: "Mi padre trabaja mucho." },
  { id: "hermano", es: "hermano", en: "brother", hint: "Hermana — sister; hermanos — siblings.", example: "Tengo dos hermanos." },
  { id: "amigo", es: "amigo", en: "friend", acceptedEn: ["buddy", "mate"], hint: "Amiga for feminine; amigos for group.", example: "Es mi mejor amigo." },
  { id: "hombre", es: "hombre", en: "man", hint: "Also filler: ¡hombre! — come on!", example: "Ese hombre es alto." },
  { id: "mujer", es: "mujer", en: "woman", hint: "Mujer can mean wife in context.", example: "Una mujer muy valiente." },
  { id: "nino", es: "niño", en: "child", acceptedEn: ["boy", "kid"], hint: "Niña — girl; niños — children.", example: "Los niños juegan en el parque." },
  { id: "cabeza", es: "cabeza", en: "head", hint: "Dolor de cabeza — headache.", example: "Me duele la cabeza." },
  { id: "mano", es: "mano", en: "hand", hint: "Echar una mano — to help out.", example: "Levanta la mano si sabes." },
  { id: "ojo", es: "ojo", en: "eye", hint: "¡Ojo! — watch out!", example: "Tiene ojos verdes." },
  { id: "corazon", es: "corazón", en: "heart", acceptedEn: ["heart"], hint: "Te quiero con todo el corazón.", example: "Late el corazón fuerte." },
  { id: "perro", es: "perro", en: "dog", hint: "Perrito — little dog, affectionate.", example: "Mi perro se llama Lola." },
  { id: "gato", es: "gato", en: "cat", hint: "Gatito — kitten vibe.", example: "El gato duerme en el sofá." },
  { id: "pajaro", es: "pájaro", en: "bird", acceptedEn: ["bird"], hint: "Pajarito — little bird.", example: "Los pájaros cantan al alba." },
  { id: "pez", es: "pez", en: "fish", acceptedEn: ["fish (animal)"], hint: "Pez alive; pescado on the plate.", example: "Vimos un pez enorme." },
  { id: "libro", es: "libro", en: "book", hint: "Librería — bookstore.", example: "Estoy leyendo un libro buenísimo." },
  { id: "musica", es: "música", en: "music", acceptedEn: ["music"], hint: "Música clásica, flamenco, reggaetón — all Spanish-speaking worlds.", example: "Escucho música mientras corro." },
  { id: "pelicula", es: "película", en: "movie", acceptedEn: ["film"], hint: "Ir al cine — go to the movies.", example: "Esa película es española." },
  { id: "trabajo", es: "trabajo", en: "work", acceptedEn: ["job"], hint: "Trabajo as noun; trabajar — to work.", example: "Tengo mucho trabajo hoy." },
  { id: "escuela", es: "escuela", en: "school", hint: "Colegio often primary; universidad — uni.", example: "Los niños van a la escuela." },
  { id: "tienda", es: "tienda", en: "shop", acceptedEn: ["store"], hint: "Tienda de campaña — tent (false friend alert!).", example: "Hay una tienda nueva en la esquina." },
  { id: "mercado", es: "mercado", en: "market", hint: "Mercado central — sensory overload.", example: "Compramos pescado en el mercado." },
  { id: "dinero", es: "dinero", en: "money", hint: "Plata — slang in many regions.", example: "No tengo dinero suelto." },
  { id: "tiempo", es: "tiempo", en: "time", acceptedEn: ["weather"], hint: "Also means weather: ¿Qué tiempo hace?", example: "No tengo tiempo libre." },
  { id: "amor", es: "amor", en: "love", hint: "Te amo / te quiero — intensity differs by region.", example: "Habla de amor y pérdida." },
  { id: "vida", es: "vida", en: "life", hint: "¡Qué vida! — what a life!", example: "La vida es corta." },
  { id: "feliz", es: "feliz", en: "happy", hint: "Feliz cumpleaños — happy birthday.", example: "Estoy muy feliz hoy." },
  { id: "triste", es: "triste", en: "sad", hint: "Tristeza — sadness; poetic in songs.", example: "Se ve triste." },
  { id: "grande", es: "grande", en: "big", acceptedEn: ["large", "great"], hint: "Gran before singular nouns: un gran día.", example: "Una ciudad muy grande." },
  { id: "pequeno", es: "pequeño", en: "small", acceptedEn: ["little"], hint: "Pequeñito — tiny cute.", example: "Un perro pequeño." },
  { id: "bueno", es: "bueno", en: "good", hint: "Bueno as filler: Bueno, pues…", example: "Buen provecho — enjoy your meal." },
  { id: "malo", es: "malo", en: "bad", hint: "Mal día — bad day.", example: "Es un mal momento." },
  { id: "nuevo", es: "nuevo", en: "new", hint: "De nuevo — again.", example: "Tengo un trabajo nuevo." },
  { id: "viejo", es: "viejo", en: "old", acceptedEn: ["elderly"], hint: "Viejo can be affectionate among friends.", example: "Un edificio muy viejo." },
  { id: "facil", es: "fácil", en: "easy", acceptedEn: ["easy"], hint: "Fácilmente — easily.", example: "El examen fue fácil." },
  { id: "dificil", es: "difícil", en: "difficult", acceptedEn: ["hard"], hint: "Dificultad — difficulty.", example: "El español no es tan difícil." },
  { id: "rapido", es: "rápido", en: "fast", acceptedEn: ["quick"], hint: "Rápido as adverb often same form.", example: "Corre muy rápido." },
  { id: "lento", es: "lento", en: "slow", hint: "Despacito — slowly, gently.", example: "El tren va lento." },
  { id: "caliente", es: "caliente", en: "hot", acceptedEn: ["warm"], hint: "Caliente thing vs. having heat — context!", example: "La sopa está caliente." },
  { id: "frio", es: "frío", en: "cold", hint: "Hace frío — it's cold out.", example: "El agua está fría." },
  { id: "bonito", es: "bonito", en: "pretty", acceptedEn: ["beautiful", "nice"], hint: "Bonito also a fish — language fun.", example: "Qué lugar tan bonito." },
  { id: "importante", es: "importante", en: "important", hint: "Importa — it matters.", example: "Es muy importante estudiar." },
  { id: "necesito", es: "necesito", en: "I need", acceptedEn: ["i need"], hint: "From necesitar; follow with noun or infinitive.", example: "Necesito ayuda, por favor." },
  { id: "quiero", es: "quiero", en: "I want", acceptedEn: ["i want", "i love"], hint: "Te quiero — I love you (often softer than te amo).", example: "Quiero un café." },
  { id: "puedo", es: "puedo", en: "I can", acceptedEn: ["i can"], hint: "Poder — can/to be able.", example: "¿Puedo entrar?" },
  { id: "tengo", es: "tengo", en: "I have", acceptedEn: ["i have"], hint: "Tener hambre — to be hungry (lit. have hunger).", example: "Tengo dos billetes." },
  { id: "hay", es: "hay", en: "there is", acceptedEn: ["there are"], hint: "Impersonal: hay mucha gente.", example: "Hay un problema." },
  { id: "donde", es: "¿dónde?", en: "where", acceptedEn: ["where?"], hint: "Accent in questions; donde = where (relative).", example: "¿Dónde está el baño?" },
  { id: "que", es: "¿qué?", en: "what", acceptedEn: ["what?"], hint: "Qué vs cual — what vs which.", example: "¿Qué hora es?" },
  { id: "cuando", es: "¿cuándo?", en: "when", acceptedEn: ["when?"], hint: "Cuando without accent = when (relative).", example: "¿Cuándo llegas?" },
  { id: "como", es: "¿cómo?", en: "how", acceptedEn: ["how?"], hint: "Cómo = how; como = like / I eat.", example: "¿Cómo se dice…?" },
  { id: "por-que", es: "¿por qué?", en: "why", acceptedEn: ["why?"], hint: "Porque (together) = because.", example: "¿Por qué estudias español?" },
  { id: "cuanto", es: "¿cuánto?", en: "how much", acceptedEn: ["how many"], hint: "Cuánto cuesta — how much does it cost.", example: "¿Cuánto vale?" },
  { id: "baño", es: "baño", en: "bathroom", acceptedEn: ["restroom", "toilet"], hint: "Servicios also used in public places.", example: "¿Dónde está el baño?" },
  { id: "entrada", es: "entrada", en: "entrance", acceptedEn: ["ticket", "starter"], hint: "Also first course or ticket stub.", example: "La entrada cuesta diez euros." },
  { id: "salida", es: "salida", en: "exit", acceptedEn: ["departure"], hint: "Follow salida signs at metros.", example: "Busca la salida de emergencia." },
  { id: "tren", es: "tren", en: "train", hint: "AVE — high-speed pride in Spain.", example: "Cogemos el tren a Sevilla." },
  { id: "avion", es: "avión", en: "airplane", acceptedEn: ["plane"], hint: "Aeropuerto — airport.", example: "El avión sale a las ocho." },
  { id: "coche", es: "coche", en: "car", acceptedEn: ["automobile"], hint: "Carro in parts of Latin America.", example: "Aparcamos el coche aquí." },
  { id: "bicicleta", es: "bicicleta", en: "bicycle", acceptedEn: ["bike"], hint: "Bici — short form.", example: "Voy en bicicleta al trabajo." },
  { id: "mapa", es: "mapa", en: "map", hint: "Mapa del metro — survival essential.", example: "Mira el mapa en el móvil." },
  { id: "hotel", es: "hotel", en: "hotel", hint: "Hostal — often budget lodging in Spain.", example: "Reservamos hotel céntrico." },
  { id: "pasaporte", es: "pasaporte", en: "passport", hint: "Keep copies separate from original.", example: "Olvidé el pasaporte en el hotel." },
  { id: "equipaje", es: "equipaje", en: "luggage", acceptedEn: ["baggage"], hint: "Facturar el equipaje — check bags.", example: "Mi equipaje es ligero." },
  { id: "ayuda", es: "ayuda", en: "help", hint: "¡Ayuda! — help! in emergencies.", example: "Necesito ayuda con la maleta." },
  { id: "peligro", es: "peligro", en: "danger", hint: "Peligro signs on cliffs and roads.", example: "No hay peligro ahora." },
  { id: "felicidades", es: "felicidades", en: "congratulations", acceptedEn: ["Congrats"], hint: "Birthdays, graduations, wins.", example: "¡Felicidades por el bebé!" },
  { id: "suerte", es: "suerte", en: "luck", hint: "¡Buena suerte! — good luck.", example: "Te deseo mucha suerte." },
  { id: "sueno", es: "sueño", en: "dream", acceptedEn: ["sleepiness"], hint: "Tener sueño — to be sleepy.", example: "Sigo un sueño viejo." },
  { id: "fuego", es: "fuego", en: "fire", hint: "¡Fuego! — fire alarm energy.", example: "El fuego calienta la sala." },
  { id: "puente", es: "puente", en: "bridge", hint: "Puente long weekend when holiday bridges days.", example: "Cruzamos el puente antiguo." },
  { id: "iglesia", es: "iglesia", en: "church", hint: "Catedral — cathedral scale.", example: "La iglesia data del siglo XII." },
  { id: "museo", es: "museo", en: "museum", hint: "Museo del Prado — Madrid treasure.", example: "El museo cierra los lunes." },
  { id: "fiesta", es: "fiesta", en: "party", acceptedEn: ["festival"], hint: "Fiesta also means holiday in towns.", example: "Hay fiesta en la plaza." },
  { id: "danza", es: "danza", en: "dance", acceptedEn: ["dancing"], hint: "Bailar — to dance; danza more formal art.", example: "La danza española es intensa." },
  { id: "cancion", es: "canción", en: "song", acceptedEn: ["song"], hint: "Canción de cuna — lullaby.", example: "Esa canción me emociona." },
  { id: "familia", es: "familia", en: "family", hint: "Familia extends wide in many cultures.", example: "Ceno con mi familia los domingos." },
  { id: "comida", es: "comida", en: "food", acceptedEn: ["meal", "lunch"], hint: "La comida can mean lunch in Spain.", example: "La comida está deliciosa." },
  { id: "bebida", es: "bebida", en: "drink", hint: "Bebida can be noun 'a beverage'.", example: "¿Qué bebida quieres?" },
  { id: "cuenta", es: "cuenta", en: "bill", acceptedEn: ["check", "account"], hint: "La cuenta, por favor — ask for the check.", example: "Traiga la cuenta cuando pueda." },
  { id: "propina", es: "propina", en: "tip", hint: "Customs vary by country — ask locals.", example: "Dejamos propina en el bar." },
  { id: "izquierda", es: "izquierda", en: "left", hint: "A la izquierda — to the left.", example: "Gira a la izquierda." },
  { id: "derecha", es: "derecha", en: "right", hint: "Todo recto — straight ahead.", example: "La farmacia está a la derecha." },
  { id: "aqui", es: "aquí", en: "here", acceptedEn: ["here"], hint: "Aquí tienes — here you go.", example: "Siéntate aquí conmigo." },
  { id: "alli", es: "allí", en: "there", acceptedEn: ["there"], hint: "Allá — further away in some dialects.", example: "El banco está allí." },
  { id: "muy", es: "muy", en: "very", hint: "Muy vs mucho — very vs a lot.", example: "Estoy muy cansado." },
  { id: "poco", es: "poco", en: "little", acceptedEn: ["a little", "few"], hint: "Un poco de — a little of.", example: "Hablo un poco de español." },
  { id: "todo", es: "todo", en: "everything", acceptedEn: ["all"], hint: "Todo el mundo — everyone (lit. all the world).", example: "Lo quiero todo." },
  { id: "nada", es: "nada", en: "nothing", hint: "De nada — you're welcome.", example: "No quiero nada más." },
  { id: "algo", es: "algo", en: "something", hint: "Algo más? — anything else?", example: "Necesito algo de agua." },
  { id: "alguien", es: "alguien", en: "someone", hint: "¿Hay alguien? — is anyone there?", example: "Alguien llamó a la puerta." },
  { id: "nadie", es: "nadie", en: "nobody", acceptedEn: ["no one"], hint: "Double negative common: no veo a nadie.", example: "Nadie sabe la respuesta." },
  { id: "siempre-listo", es: "listo", en: "ready", acceptedEn: ["smart", "clever"], hint: "In Spain listo also means clever; 'ready' in Latin America often.", example: "¿Estás listo para salir?" },
  { id: "cansado", es: "cansado", en: "tired", hint: "Cansancio — fatigue.", example: "Estoy cansado de correr." },
  { id: "hambre", es: "hambre", en: "hunger", hint: "Tengo hambre — I'm hungry.", example: "Muero de hambre." },
  { id: "sed", es: "sed", en: "thirst", hint: "Tengo sed — I'm thirsty.", example: "Bebo agua porque tengo sed." },
  { id: "pregunta", es: "pregunta", en: "question", hint: "Hacer una pregunta — to ask.", example: "Tengo una pregunta rápida." },
  { id: "respuesta", es: "respuesta", en: "answer", hint: "Sin respuesta — unanswered.", example: "Busco la respuesta correcta." },
  { id: "palabra", es: "palabra", en: "word", hint: "Palabra Vortex — you're in it!", example: "Cada palabra cuenta." },
  { id: "frase", es: "frase", en: "phrase", acceptedEn: ["sentence"], hint: "Frase hecha — idiom.", example: "Aprende frases enteras, no solo palabras." },
  { id: "idioma", es: "idioma", en: "language", hint: "Lengua also means language / tongue.", example: "El español es un idioma hermoso." },
  { id: "practica", es: "práctica", en: "practice", hint: "Practicar — to practice.", example: "La práctica hace al maestro." },
];

export const PALABRA_BANK_COUNT = PALABRA_WORD_BANK.length;
